### ISSUE TITLE
Missing modules in backbone folder

### ISSUE THREAD

**Issue by jiany-ctrl** [YangLiu9208/SAKDN#2]
(1) No ResNet18, ResNet50, VggNet16, SeVggNet16, SeFusionVGG16, SemanticFusionVGG16 in the backbone folder, No LinearEmbedding in model.embedding. 
(2)  Can you please kindly share the requirements.txt?
(3) With no VggNet16, I downloaded a vgg file from torchvision zoo (https://github.com/pytorch/vision/blob/master/torchvision/models/vgg.py), and I get an error message: TypeError: forward() got an unexpected keyword argument 'n_classes'.

**Comment by YangLiu9208** [comment]
(1) All the backbones are uploaded https://github.com/YangLiu9208/SAKDN/blob/master/model.rar
(2) The model zoo are in the rar files tf_model_zoo.part1-3.rar.
