### ISSUE TITLE
Codebase for another related paper

### ISSUE THREAD

**Issue by Aiiiiii** [YangLiu9208/SAKDN#3]
Hi Yang liu,

Hope you're doing well!

I am reading your recent related paper "CROSS-MODAL KNOWLEDGE DISTILLATION FOR VISION-TO-SENSOR ACTION RECOGNITION" and want to use the model as one of the baselines in our project, but I didn't find the codebase for this paper. I was hoping if you may kindly share the code for your paper as it'd be extremely helpful in our work. 

Thank you.

**Comment by YangLiu9208** [comment]
You can contact Dr. Jianyuan Ni (j_n317@txstate.edu) for code.

**Comment by Aiiiiii** [comment]
@YangLiu9208 Thanks for sharing the contact information.
